#!/usr/bin/env python3
"""
Normalize low-quality generic flashcard questions.

Targets questions generated by fallback templates such as:
- "Consolidation XX ..."
- "... quel principe cle faut-il retenir ..."

The script rewrites only the question (and optionally appends a migration note
in explication) while preserving existing answers.
"""

from __future__ import annotations

import argparse
import re
import sqlite3
import unicodedata
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_DB = REPO_ROOT / "data" / "iaca.db"
STOPWORDS = {
    "dans", "avec", "pour", "sans", "plus", "moins", "cette", "cela", "comme", "dont", "ainsi",
    "leur", "leurs", "elles", "entre", "apres", "avant", "tres", "tout", "tous", "toutes",
    "etre", "avoir", "sont", "ete", "sur", "par", "des", "les", "une", "que", "qui", "est",
    "aux", "ces", "ses", "son", "nos", "vos", "car", "pas", "mais", "donc", "cet", "cette",
    "cours", "licence", "annee", "section", "chapitre", "document", "point", "premier", "lieu",
    "suivante", "notion", "retenir", "passage", "partie",
}


def normalize(text: str) -> str:
    lowered = text.lower().strip()
    lowered = unicodedata.normalize("NFKD", lowered)
    lowered = "".join(ch for ch in lowered if not unicodedata.combining(ch))
    lowered = re.sub(r"\s+", " ", lowered)
    return lowered


def clean_text(text: str) -> str:
    cleaned = re.sub(r"\s+", " ", (text or "").strip())
    return cleaned


def slug_from_url(text: str) -> str:
    urls = re.findall(r"https?://\S+", text)
    if not urls:
        return ""
    last = urls[0].rstrip("/").split("/")[-1]
    last = re.sub(r"\?.*$", "", last)
    last = re.sub(r"[-_]+", " ", last)
    last = re.sub(r"[^A-Za-z0-9À-ÿ ]", " ", last)
    last = re.sub(r"\s+", " ", last).strip()
    return last[:80]


def best_snippet(answer: str) -> str:
    text = clean_text(answer)
    if not text:
        return ""

    # Remove obvious URL-only payload from the generic source.
    no_urls = re.sub(r"https?://\S+", " ", text)
    no_urls = re.sub(r"\s+", " ", no_urls).strip()

    # Keep first meaningful chunk.
    candidates = re.split(r"[.;:!?]\s+|\n+", no_urls)
    for candidate in candidates:
        candidate = candidate.strip(" -•\t")
        if len(candidate) >= 18:
            return candidate[:120]

    if no_urls:
        return no_urls[:120]

    return ""


def build_question(matiere: str, answer: str) -> str:
    subject = matiere or "cette matiere"
    snippet = best_snippet(answer)
    if snippet:
        words = re.findall(r"[A-Za-zÀ-ÿ][A-Za-zÀ-ÿ'-]{3,}", snippet.lower())
        topics: list[str] = []
        seen: set[str] = set()
        for word in words:
            if word in STOPWORDS or word in seen:
                continue
            seen.add(word)
            topics.append(word)
            if len(topics) >= 4:
                break

        if topics:
            topic_label = " / ".join(topics)
            return f"En {subject}, comment definir la notion de '{topic_label}' ?"

    if snippet:
        return f"En {subject}, a quoi renvoie la notion suivante: '{snippet}' ?"

    slug = slug_from_url(answer)
    if slug:
        return f"En {subject}, quel theme est traite par la ressource '{slug}' ?"

    return ""


def main() -> int:
    parser = argparse.ArgumentParser(description="Fix generic flashcard questions in DB.")
    parser.add_argument("--db-path", default=str(DEFAULT_DB), help="Path to SQLite database")
    parser.add_argument("--apply", action="store_true", help="Apply updates (default: dry-run)")
    parser.add_argument("--limit", type=int, default=0, help="Max rows to process (0 = all)")
    parser.add_argument("--sample", type=int, default=10, help="Number of examples to print")
    args = parser.parse_args()

    db_path = Path(args.db_path)
    if not db_path.exists():
        raise SystemExit(f"DB not found: {db_path}")

    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()

    query = """
        SELECT f.id, f.question, f.reponse, f.explication, COALESCE(m.nom, 'General') AS matiere
        FROM flashcards f
        LEFT JOIN matieres m ON m.id = f.matiere_id
        WHERE LOWER(COALESCE(f.question, '')) LIKE 'consolidation %'
           OR LOWER(COALESCE(f.question, '')) LIKE '%quel principe cle faut-il retenir%'
           OR LOWER(COALESCE(f.question, '')) LIKE '%quel principe clé faut-il retenir%'
        ORDER BY f.id
    """

    rows = cur.execute(query).fetchall()
    if args.limit > 0:
        rows = rows[: args.limit]

    processed = 0
    updated = 0
    skipped = 0
    samples: list[tuple[int, str, str]] = []

    for row in rows:
        processed += 1
        old_question = clean_text(row["question"] or "")
        new_question = build_question(row["matiere"], row["reponse"] or "")

        if not new_question:
            skipped += 1
            continue

        if normalize(old_question) == normalize(new_question):
            skipped += 1
            continue

        explication = row["explication"] or ""
        migration_note = "[Migration P19-3: question normalisee]"
        if migration_note not in explication:
            explication = (explication + " " + migration_note).strip()

        if args.apply:
            cur.execute(
                "UPDATE flashcards SET question = ?, explication = ? WHERE id = ?",
                (new_question[:280], explication, row["id"]),
            )

        updated += 1
        if len(samples) < args.sample:
            samples.append((row["id"], old_question, new_question))

    if args.apply:
        conn.commit()
    conn.close()

    mode = "APPLY" if args.apply else "DRY-RUN"
    print(f"mode={mode}")
    print(f"processed={processed}")
    print(f"updated={updated}")
    print(f"skipped={skipped}")
    print("samples:")
    for sid, old_q, new_q in samples:
        print(f"- id={sid}")
        print(f"  old: {old_q}")
        print(f"  new: {new_q}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
